### ISSUE TITLE
Please clarify the need and effectiveness of check_cmdline ()

### ISSUE THREAD

**Issue by ranolfi** [grazzolini/mkinitcpio-chkcryptoboot#13]
Dear developer,

I'm having difficulty understanding the effectiveness of checking for the kernel command-line parameters.

It is said that:

> This allows the hook to detect if GRUB's configuration was not bypassed at run-time and afterwards to detect if the entire /boot partition was not bypassed.

However:

1. The check resides in the `initramfs`, which is itself in the `/boot` partition. But so is `grub.cfg`. An attacker will most likely pay attention to the command line parameters in that file and replicate them - in fact, some of them are often needed to successfully boot a system.

2. If the entire `/boot` partition is bypassed, we presume that both the default kernel _and_ the `initramfs` are **not** loaded. So, how is the check going to be useful?

Thank you.

**Comment by grazzolini** [comment]
This check also is ran after the system is booted, so you can detect a bypass. Also, please see #14
