### ISSUE TITLE
Install hook fails if the EFI stub location contains space

### ISSUE THREAD

**Issue by ranolfi** [grazzolini/mkinitcpio-chkcryptoboot#9]
My bootloader ID is "Arch Linux".

This is how I configured my chkcryptoboot.conf file:

`EFISTUB=/boot/efi/EFI/Arch\ Linux/grubx64.efi`

But when running `mkinitcpio`, the chkcryptoboot hook will fail with this error in line 39:

> [: too many arguments

I solved this by surrounding `$EFISTUB` with double quotes in lines 39 and 49 of file `install/chkcryptoboot`.

**Comment by grazzolini** [comment]
This is a bug, I have just fixed this on #15 and a new release of chkcryptoboot will contain this.
